## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
from sklearn.model_selection import train_test_split


import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

?train_test_split

In [3]:
y1_index = range(40)
y0_index = range(40,200)

In [4]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X[y1_index],y[y1_index], random_state=16, test_size=10)
X0_train, X0_test, y0_train, y0_test = train_test_split(X[y0_index],y[y0_index],random_state=16, test_size=10)

In [5]:
X1_test
X0_test

array([[465, 466, 467, 468, 469],
       [235, 236, 237, 238, 239],
       [755, 756, 757, 758, 759],
       [885, 886, 887, 888, 889],
       [700, 701, 702, 703, 704],
       [860, 861, 862, 863, 864],
       [890, 891, 892, 893, 894],
       [500, 501, 502, 503, 504],
       [870, 871, 872, 873, 874],
       [880, 881, 882, 883, 884]])

In [6]:
X_test=np.concatenate([X1_test, X0_test])
X_train = np.concatenate([X1_train, X0_train])
y_train=np.concatenate([y1_train, y0_train])
y_test=np.concatenate([y1_test, y0_test])

In [7]:
X_test

array([[ 55,  56,  57,  58,  59],
       [ 75,  76,  77,  78,  79],
       [180, 181, 182, 183, 184],
       [110, 111, 112, 113, 114],
       [ 95,  96,  97,  98,  99],
       [ 15,  16,  17,  18,  19],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [105, 106, 107, 108, 109],
       [ 85,  86,  87,  88,  89],
       [465, 466, 467, 468, 469],
       [235, 236, 237, 238, 239],
       [755, 756, 757, 758, 759],
       [885, 886, 887, 888, 889],
       [700, 701, 702, 703, 704],
       [860, 861, 862, 863, 864],
       [890, 891, 892, 893, 894],
       [500, 501, 502, 503, 504],
       [870, 871, 872, 873, 874],
       [880, 881, 882, 883, 884]])

In [8]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [9]:
y_train

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])